# Generated by Django 3.0.6 on 2020-06-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
                ('description', models.CharField(default=None, max_length=100)),
                ('imgJoueur', models.ImageField(blank=True, upload_to='images_joueur')),
                ('club', models.CharField(default=None, max_length=30)),
                ('pays', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
                ('description', models.CharField(default=None, max_length=100)),
                ('imgVille', models.ImageField(blank=True, upload_to='images_places')),
                ('price', models.CharField(default=None, max_length=30)),
            ],
        ),
    ]
